# Generated by Django 3.2.25 on 2024-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_siteuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
