# Generated by Django 3.2.25 on 2024-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240708_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
