# Generated by Django 3.2.25 on 2024-07-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userpaymentmethod_account_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
