# Generated by Django 3.2.25 on 2024-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
