# Generated by Django 3.2.25 on 2024-07-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderstatus_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus'),
        ),
    ]
