# Generated by Django 3.2.25 on 2024-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20240714_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='order_total',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
