# Generated by Django 3.2.25 on 2024-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, default='category_images/default.jpg', null=True, upload_to='category_images/'),
        ),
    ]
