# Generated by Django 3.2.25 on 2024-07-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240709_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconfiguration',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productconfiguration',
            name='qty_in_stock',
            field=models.IntegerField(default=0),
        )
    ]
